name: ci

on:
  push:
    branches: [master]
    paths: [resume.json, profile.jpg, generate-pdf.js, package.json, package-lock.json, .github/workflows/ci.yaml]
  pull_request:
    branches: [master]
    paths: [resume.json, profile.jpg, generate-pdf.js, package.json, package-lock.json, .github/workflows/ci.yaml]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npm run generate-pdf

      # Publish steps, only runs when pushing to the default branch
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Update latest tag
        uses: EndBug/latest-tag@v1
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Create Release with PDF
        uses: softprops/action-gh-release@v1
        with:
          name: PDF
          body: The latest resume in PDF format.
          tag_name: latest
          files: resume.pdf
          fail_on_unmatched_files: true
