name: ci

on:
  push:
    branches: [master]
    paths: [resume.json, profile.jpg, package.json, .github/workflows/ci.yaml]
  pull_request:
    branches: [master]
    paths: [resume.json, profile.jpg, package.json, .github/workflows/ci.yaml]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install
      - run: npm run build
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
